Warning message:
[1] "Error in file(filename, \"r\", encoding = encoding): cannot open the connection\n"
In file(filename, "r", encoding = encoding) :
  cannot open file '/Users/blerner/Documents/Process/DataProvenance/github/RDataTracker/R/DDGCheckpoint.R': No such file or directory
Error in as.POSIXct(time2) : object 'startTime' not found
Calls: cat -> difftime -> as.POSIXct
Execution halted
